const {
  getAllCompanies,
  signupCompany,
  loginCompany,
  profileData,
  addMainStructure,
  allStructures,
  deleteMainStructure,
  updateMainStructure,
  deleteCompany,
  profileDataAbout,
  profileDataSocial,
  profileDataMainStructure,
  profileDataBranches,
  profileDataStaff,
  profileDataOutsource,
  profileDataClients,
  profileDataPic,
  uploadImage,
} = require("./companyController");

const { adminLogin, adminReg, getAdmins } = require("./adminController");

module.exports = {
  getAllCompanies,
  signupCompany,
  loginCompany,
  profileData,
  addMainStructure,
  adminLogin,
  adminReg,
  getAdmins,
  allStructures,
  deleteMainStructure,
  updateMainStructure,
  deleteCompany,
  profileDataAbout,
  profileDataSocial,
  profileDataMainStructure,
  profileDataBranches,
  profileDataStaff,
  profileDataOutsource,
  profileDataClients,
  profileDataPic,
  uploadImage,
};
